name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          #mdbook-version: '0.4.10'
          mdbook-version: 'latest'

      - run: mdbook build vuu-book

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          #github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./vuu-book/book