name: Deploy to MVN Central

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y-SNAPSHOT"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Set up JDK 1.16
        uses: actions/setup-java@v1
        with:
          java-version: 1.16
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - id: install-gpg-cert
        name: Install GPG secret key
        run: | 
            cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --yes --always-trust --import
#        env:
#          GPG_TTY: $(tty)
      - name: Build with Maven
        run: mvn -X --no-transfer-progress release:prepare release:perform  -P sign-it -Dsign=true -Darguments=-Dgpg.passphrase=Grumbl3b0y! -Dgpg.passphrase=Grumbl3b0y! -s .settings/settings.xml -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
        env:
#          GPG_TTY: $(tty)
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHASE }}
